/**
 * emailService.js
 * ---------------
 * Reusable EmailJS utility for Learning Loops.
 *
 * Responsibilities:
 *   - sendOTPEmail(email, passcode)        → uses OTP template
 *   - sendPasswordResetEmail(email, link)  → uses password-reset template
 *
 * EmailJS is used ONLY as the email delivery transport.
 * OTP generation and validation are handled by the Express backend.
 *
 * Template variable names must exactly match the EmailJS template:
 *   OTP template:            {{email}}, {{passcode}}
 *   Password reset template: {{email}}, {{link}}
 */

import emailjs from '@emailjs/browser';

const SERVICE_ID  = import.meta.env.VITE_EMAILJS_SERVICE_ID;
const OTP_TMPL    = import.meta.env.VITE_EMAILJS_OTP_TEMPLATE_ID;
const RESET_TMPL  = import.meta.env.VITE_EMAILJS_PASSWORD_RESET_TEMPLATE_ID;
const PUBLIC_KEY  = import.meta.env.VITE_EMAILJS_PUBLIC_KEY;

/**
 * Send a 6-digit OTP to the user's email for account verification.
 *
 * @param {string} email    - Recipient email address
 * @param {string} passcode - 6-digit OTP generated by the backend
 * @returns {Promise<{ success: boolean, error?: string }>}
 */
export const sendOTPEmail = async (email, passcode) => {
  if (!SERVICE_ID || !OTP_TMPL || !PUBLIC_KEY) {
    return { success: false, error: 'EmailJS is not configured. Check environment variables.' };
  }

  try {
    await emailjs.send(
      SERVICE_ID,
      OTP_TMPL,
      { email, passcode },
      { publicKey: PUBLIC_KEY }
    );
    return { success: true };
  } catch (err) {
    // Do not log OTP values in production
    const message = err?.text || err?.message || 'Failed to send OTP email.';
    return { success: false, error: message };
  }
};

/**
 * Send a password-reset email.
 * The `link` parameter contains the reset code (or reset URL if switched to link-based flow later).
 *
 * @param {string} email - Recipient email address
 * @param {string} link  - Reset code or URL to include in the email
 * @returns {Promise<{ success: boolean, error?: string }>}
 */
export const sendPasswordResetEmail = async (email, link) => {
  if (!SERVICE_ID || !RESET_TMPL || !PUBLIC_KEY) {
    return { success: false, error: 'EmailJS is not configured. Check environment variables.' };
  }

  try {
    await emailjs.send(
      SERVICE_ID,
      RESET_TMPL,
      { email, link },
      { publicKey: PUBLIC_KEY }
    );
    return { success: true };
  } catch (err) {
    const message = err?.text || err?.message || 'Failed to send password reset email.';
    return { success: false, error: message };
  }
};
